apiVersion: v1
data:
  config.js: |-
    window.ENV = {
      "API_URL":"http://localhost:8080",
      "API_KEY":"	43fbc9b33302db65d58553e27d1679ac"
    }
kind: ConfigMap
metadata:
  name: client
  labels:
    app: client
    app.kubernetes.io/name: client
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: client
