apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../bases

namespace: product-catalog-dev

patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: client
  path: patch-client-deployment.yml

- target:
    group: apps.openshift.io
    version: v1
    kind: DeploymentConfig
    name: server
  path: patch-server-deploymentconfig.yml
