---
- name: Create Server S2I
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/server-binary-s2i.yml') }}"
    namespace: "{{ namespace }}"

- name: Create Client S2I
  k8s:
    state: present
    definition: "{{ lookup('template', './templates/client-binary-s2i.yml') }}"
    namespace: "{{ namespace }}"