apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: client
spec:
   workspaces:
    - name: app-binary
   resources:
    - name: source
      type: git
    - name: internal-image
      type: image
    - name: repository-image
      type: image
   params:
     - name: push-image
       type: string
   tasks:
    - name: build
      taskRef:
        name: npm
      workspaces:
        - name: app-binary
          workspace: app-binary
      resources:
        inputs:
        - name: source
          resource: source
    - name: build-image
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: app-binary
      runAfter:
        - build
      params:
        - name: COMMANDS
          value: |
              ls $(workspaces.app-binary.path)
              oc start-build client --from-dir=$(workspaces.app-binary.path) --wait=true
    - name: deploy-dev
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: app-binary
      runAfter:
        - build-image
      params:
        - name: COMMANDS
          value: |
              oc tag product-catalog-cicd/client:latest product-catalog-dev/client:latest
              oc rollout restart deployment/client -n product-catalog-dev
              oc scale deployment/client --replicas=2 -n product-catalog-dev
    - name: promote-image
      conditions:
      - conditionRef: push-image
        params:
          - name: push
            value: "$(params.push-image)"
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - deploy-dev
      resources:
        inputs:
        - name: src-image
          resource: internal-image
        - name: dest-image
          resource: repository-image
    - name: deploy-test
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: app-binary
      runAfter:
        - promote-image
      params:
        - name: COMMANDS
          value: |
              oc tag product-catalog-dev/client:latest product-catalog-test/client:latest
              oc rollout restart deployment/client -n product-catalog-test
              oc scale deployment/client --replicas=2 -n product-catalog-test