apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Tekton tasks
- task-maven.yml
- task-npm.yml
- task-oc.yml
- task-push-image.yml
- condition-push-image.yml
# Server pipeline
- server-dest-image-resource.yml
- server-src-image-resource.yml
- server-imagestream.yml
- server-buildconfig.yml
- server-pvc.yml
- server-git-pipelineresource.yml
- server-pipeline.yml
- server-pipelinerun.yml
# Client pipeline
- client-dest-image-resource.yml
- client-src-image-resource.yml
- client-imagestream.yml
- client-buildconfig.yml
- client-pvc.yml
- client-git-pipelineresource.yml
- client-pipeline.yml
- client-pipelinerun.yml