apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: server
  generateName: server-
spec:
  pipelineRef:
    name: server
  resources:
    - name: source
      resourceRef:
        name: server
    - name: internal-image
      resourceRef:
        name: server-src-image
    - name: repository-image
      resourceRef:
        name: server-dest-image
  workspaces:
  - name: app-binary
    persistentVolumeClaim:
      claimName: server-binary