apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: server
  generateName: server-
spec:
  pipelineRef:
    name: server
  resources:
    - name: source
      resourceRef:
        name: server
  workspaces:
  - name: app-binary
    persistentVolumeClaim:
      claimName: server-binary