apiVersion: v1
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: {{database_name}}
stringData:
  database-name: {{database_name}}
  database-password: {{database_password}}
  database-root-password: {{database_password}}
  database-user: {{database_user}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{database_name}}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{database_size|default("1Gi", true)}}
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{database_name}}
  labels:
    app: {{database_name}}
    app.kubernetes.io/name: {{database_name}}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: {{application}}
    app.kubernetes.io/instance: database
    app.openshift.io/runtime: mariadb    
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        alpha.image.policy.openshift.io/resolve-names: '*'
      labels:
        name: {{database_name}}
    spec:
      containers:
        - name: {{database_name}}
          image: registry.redhat.io/rhel8/mariadb-103:1
          imagePullPolicy: Always
          ports:
          - containerPort: 3306
          env:
            - name: MYSQL_USER
              valueFrom:
                secretKeyRef:
                  name: {{database_name}}
                  key: database-user
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{database_name}}
                  key: database-password
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{database_name}}
                  key: database-root-password
            - name: MYSQL_DATABASE
              valueFrom:
                secretKeyRef:
                  name: {{database_name}}
                  key: database-name
          readinessProbe:
            exec:
              command:
              - /bin/sh
              - -i
              - -c
              - MYSQL_PWD="$MYSQL_PASSWORD" mysql -h 127.0.0.1 -u $MYSQL_USER -D $MYSQL_DATABASE
                -e 'SELECT 1'
            initialDelaySeconds: 5
            timeoutSeconds: 1
          livenessProbe:
            initialDelaySeconds: 30
            tcpSocket:
              port: 3306
            timeoutSeconds: 1
          volumeMounts:
          - mountPath: /var/lib/mysql/data
            name: {{database_name}}-data
      volumes:
      - name: {{database_name}}-data
        persistentVolumeClaim:
          claimName: {{database_name}}
---
apiVersion: v1
kind: Service
metadata:
  app: {{database_name}}
  name: {{database_name}}
spec:
  ports:
  - name: tcp
    port: 3306
  selector:
    name: {{database_name}}