apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: server
spec:
   resources:
    - name: source
      type: git
    - name: internal-image
      type: image
    - name: repository-image
      type: image
   params:
    - name:  MAVEN_MIRROR_URL
      default: ""
    - name: REPLICAS
      default: "1"
   tasks:
    - name: build
      taskRef:
        name: maven
      workspaces:
        - name: app-binary
          workspace: app-binary
      resources:
        inputs:
        - name: source
          resource: source
      params:
        - name: MAVEN_MIRROR_URL
          value: "$(params.MAVEN_MIRROR_URL)"
    - name: build-image
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: app-binary
      runAfter:
        - build
      params:
        - name: COMMANDS
          value: |
              ls $(workspaces.app-binary.path)
              oc start-build server --from-dir=$(workspaces.app-binary.path) --wait=true
    - name: promote-image
      taskRef:
        name: push-image
        kind: Task
      runAfter:
        - build-image
      resources:
        inputs:
        - name: src-image
          resource: internal-image
        - name: dest-image
          resource: repository-image
    - name: deploy-dev
      taskRef:
        name: deploy
        kind: Task
      runAfter:
        - promote-image
      params:
        - name: NAME
          value: server
        - name: NAMESPACE
          value: product-catalog-dev
        - name: REPLICAS
          value: "$(params.REPLICAS)"
    - name: deploy-test
      taskRef:
        name: deploy
        kind: Task
      runAfter:
        - deploy-dev
      params:
        - name: NAME
          value: server
        - name: NAMESPACE
          value: product-catalog-test
        - name: REPLICAS
          value: "$(params.REPLICAS)"