apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../bases

resources:
- server-dest-image-resource.yml
- server-src-image-resource.yml
- client-dest-image-resource.yml
- client-src-image-resource.yml

patchesStrategicMerge:
- patch-server-pipeline.yml
- patch-client-pipeline.yml
- patch-server-pipelinerun.yml
- patch-client-pipelinerun.yml