apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: server-src-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/product-catalog-cicd/server:latest
