apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: client
spec:
  resources:
    - name: source
      resourceRef:
        name: client
    - name: internal-image
      resourceRef:
        name: server-src-image
    - name: repository-image
      resourceRef:
        name: server-dest-image
