#########################################################
# Parameters you do need to change
#########################################################
# OCP wildcard subdomain
ocp_subdomain: apps.cluster.ocplab.com
#ocp_subdomain: apps-crc.testing

# Whether to dpeloy prometheus/grafana
# monitoring: true

#########################################################
# Optional parameters
#########################################################
# Set the type of CI/CD to use, can be jenkins or tekton
cicd_type: tekton

# Prefix to use for all of the projects. If you change the value,
# Jenkins pipelines will need to be adjusted since they are in repos
project_prefix: product-catalog

# If you fork the repos change the below
git_repo_owner: gnunn1

# If you want to use an enterprise registry with the demo
# Only supported with tekton right now
use_enterprise_registry: false
# Friendly name used when naming various k8s objects like secrets
registry_name: quay
registry_uri: quay.io
registry_username: gnunn
server_image_repository: gnunn/server
client_image_repository: gnunn/client

#########################################################
# Parameters you do not need to change
#########################################################

# Paramaters to use for postgres Database
database_name: productdb
database_user: productdb
database_password: Demo1234
database_url: jdbc:mariadb://productdb:3306/productdb

application: product-catalog

# Not supported at this time, leave false
quarkus_native_compilation: false
