---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: product-catalog-git-source
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/gnunn1/quarkus-product-catalog
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: m2-cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi