apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: java-binary
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: server
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: https://github.com/gnunn1/product-catalog-server
---
{% if use_enterprise_registry %}
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: server-internal-image
spec:
  type: image
  params:
  - name: url
    value: image-registry.openshift-image-registry.svc:5000/{{project_prefix}}-dev/server:latest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: server-repository-image
spec:
  type: image
  params:
  - name: url
    value: {{registry_uri}}/{{server_image_repository}}:latest
---
{% endif %}

apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: server
spec:
   workspaces:
    - name: java-binary
   resources:
    - name: source
      type: git
{% if use_enterprise_registry %}
    - name: internal-image
      type: image
    - name: repository-image
      type: image
{% endif %}
   tasks:
    - name: java-build
      taskRef:
        name: java-build
      workspaces:
        - name: app-binary
          workspace: java-binary
      resources:
        inputs:
        - name: source
          resource: source
    - name: build-image
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: java-binary
      runAfter:
        - java-build
      params:
        - name: COMMANDS
          value: |
              ls $(workspaces.app-binary.path)
              oc start-build server --from-dir=$(workspaces.app-binary.path) --wait=true -n {{project_prefix}}-dev
    - name: deploy-dev
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: java-binary
      runAfter:
        - build-image
      params:
        - name: COMMANDS
          value: |
              oc rollout latest dc/server -n {{project_prefix}}-dev
              oc scale dc/server --replicas=2 -n {{project_prefix}}-dev
{% if use_enterprise_registry %}
    - name: promote-image
      taskRef:
        name: mirror-image
        kind: Task
      runAfter:
        - deploy-dev
      resources:
        inputs:
        - name: src-image
          resource: internal-image
        - name: dest-image
          resource: repository-image
{% endif %}
    - name: deploy-test
      taskRef:
        name: openshift-client
        kind: Task
      workspaces:
        - name: app-binary
          workspace: java-binary
{% if use_enterprise_registry %}
      runAfter:
        - promote-image
{% else %}
      runAfter:
        - deploy-dev
{% endif %}
      params:
        - name: COMMANDS
          value: |
              oc tag {{project_prefix}}-dev/server:latest {{project_prefix}}-test/server:latest
              oc rollout latest dc/server -n {{project_prefix}}-test
              oc scale dc/server --replicas=2 -n {{project_prefix}}-test
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: server
  generateName: server-
spec:
  pipelineRef:
    name: server
  resources:
    - name: source
      resourceRef:
        name: server
{% if use_enterprise_registry %}
    - name: internal-image
      resourceRef:
        name: server-internal-image
    - name: repository-image
      resourceRef:
        name: server-repository-image
{% endif %}
  workspaces:
  - name: java-binary
    persistentVolumeClaim:
      claimName: java-binary