---
- name: Create pipeline resources
  k8s:
    state: present
    definition: "{{ lookup('file', './files/resources.yml') }}"
    namespace: "{{ namespace }}"

- name: Create pipeline task
  k8s:
    state: present
    definition: "{{ lookup('file', './files/tasks/quarkus-image-from-git.yml') }}"
    namespace: "{{ namespace }}"

- name: Create pipeline
  k8s:
    state: present
    definition: "{{ lookup('file', './files/pipelines/product-catalog-pipeline.yml') }}"
    namespace: "{{ namespace }}"
