---
- name: Create base
  k8s:
    state: present
    definition: "{{ lookup('file', './files/{{ item }}') }}"
    namespace: "{{ namespace }}"
  with_items:
    - rolebinding.yml

- name: Create pipeline tasks
  k8s:
    state: present
    definition: "{{ lookup('file', './files/tasks/{{ item }}') }}"
    namespace: "{{ namespace }}"
  with_items:
    - nodejs-build.yml
    - oc.yml
    - java-build.yml

- name: Create pipelines
  k8s:
    state: present
    definition: "{{ lookup('file', './files/pipelines/{{ item }}') }}"
    namespace: "{{ namespace }}"
  with_items:
    - client.yml
    - server.yml