#############################################################
# Provision Demo into OpenShift/Kubernetes
#############################################################
- name: Install Demo
  hosts: localhost

  vars_files:
    - vars/vars.yml

  roles:
  - { role: init-project, project: '{{project_prefix}}-cicd' }
  - { role: init-project, project: '{{project_prefix}}-dev' }
  - { role: init-project, project: '{{project_prefix}}-test' }
  - { role: deploy-mariadb, namespace: '{{project_prefix}}-dev'}
  - { role: deploy-mariadb, namespace: '{{project_prefix}}-test'}
  - { role: deploy-client, namespace: '{{project_prefix}}-dev'}
  - { role: deploy-client, namespace: '{{project_prefix}}-test'}
  - { role: deploy-server, namespace: '{{project_prefix}}-dev'}
  - { role: deploy-dev-s2i, namespace: '{{project_prefix}}-dev'}
  - { role: deploy-server, namespace: '{{project_prefix}}-test'}
  # - { role: deploy-nexus, namespace: '{{project_prefix}}-cicd'}
  - { role: deploy-pipeline, namespace: '{{project_prefix}}-cicd', when: cicd_type=="jenkins"}
  - { role: deploy-tekton-pipeline, namespace: '{{project_prefix}}-cicd', when: cicd_type=="tekton"}
  # - { role: init-project, project: '{{project_prefix}}-monitoring', when: monitoring }
  # - { role: deploy-monitoring, namespace: '{{project_prefix}}-monitoring', when: monitoring }