---
- name: Uninstall Demo
  hosts: localhost

  vars_files:
    - vars/vars.yml

  roles:
  - { role: delete-project, project: '{{project_prefix}}-cicd' }
  - { role: delete-project, project: '{{project_prefix}}-dev' }
  - { role: delete-project, project: '{{project_prefix}}-test' }