apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: product-catalog-dev
spec:
  template:
    spec:
      containers:
        - name: server
          env:
          - name: CORS_ORIGIN
            value: http://client-product-catalog-dev.apps.cluster.ocplab.com
          image: quay.io/gnunn/server:latest
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  namespace: product-catalog-test
spec:
  template:
    spec:
      containers:
        - name: server
          env:
          - name: CORS_ORIGIN
            value: http://client-product-catalog-test.apps.cluster.ocplab.com
          image: quay.io/gnunn/server:latest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: server-dest-image
spec:
  params:
  - name: url
    value: quay.io/gnunn/server:latest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: client-dest-image
spec:
  params:
  - name: url
    value: quay.io/gnunn/client:latest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client
  namespace: product-catalog-dev
data:
  config.js: |-
    window.ENV = {
      "API_URL":"http://server-product-catalog-dev.apps.cluster.ocplab.com",
      "API_KEY":"	43fbc9b33302db65d58553e27d1679ac"
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: client
  namespace: product-catalog-test
data:
  config.js: |-
    window.ENV = {
      "API_URL":"http://server-product-catalog-test.apps.cluster.ocplab.com",
      "API_KEY":"	43fbc9b33302db65d58553e27d1679ac"
    }