apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: client-binary
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
