apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
# Nexus
- github.com/redhat-canada-gitops/10-devtools//nexus2/base/?ref=master
# Supporting infra
- m2-cache-pvc.yml
# Tekton tasks
- task-maven.yml
- task-npm.yml
- task-oc.yml
- task-push-image.yml
- task-deploy.yml
- condition-push-image.yml
# Server pipeline
- server-imagestream.yml
- server-buildconfig.yml
- server-pvc.yml
- server-git-pipelineresource.yml
- server-pipeline.yml
- server-pipelinerun.yml
# Client pipeline
- client-imagestream.yml
- client-buildconfig.yml
- client-pvc.yml
- client-git-pipelineresource.yml
- client-pipeline.yml
- client-pipelinerun.yml