apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: push-image
spec:
  workspaces:
  - name: app-binary
  inputs:
    resources:
      - name: src-image
        type: image
      - name: dest-image
        type: image
  steps:
    - name: run-commands
      image: quay.io/gnunn/skopeo:latest
      script: |
        #!/usr/bin/env bash
        echo "Copying image docker://$(inputs.resources.src-image.url) to docker://$(inputs.resources.dest-image.url)"
        TOKEN="$(oc whoami -t)"
        USER="pipeline"
        skopeo copy --src-tls-verify=false --dest-tls-verify=false --src-creds="${USER}:${TOKEN}" --dest-authfile=/workspace/dest/.docker/config.json docker://$(inputs.resources.src-image.url) docker://$(inputs.resources.dest-image.url)
      volumeMounts:
        - name: dest-docker-config
          mountPath: /workspace/dest/.docker/
  volumes:
    - name: dest-docker-config
      secret:
        secretName: dest-docker-config
        items:
          - key: .dockerconfigjson
            path: config.json