apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: java-build
spec:
  workspaces:
  - name: app-binary
  inputs:
    resources:
      - name: source
        type: git
  steps:
    - name: mvn-package
      image: registry.redhat.io/openjdk/openjdk-8-rhel8:latest
      command:
        - /bin/sh
        - -c
      args:
        - mvn package
      workingDir: /workspace/source
    - name: mvn-copy-dist
      image: registry.redhat.io/openjdk/openjdk-8-rhel8:latest
      command:
        - /bin/sh
        - -c
      args:
        - cp -R ./target/*-runner.jar $(workspaces.app-binary.path)
      workingDir: /workspace/source