apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: nodejs-build
spec:
  workspaces:
  - name: app-binary
  inputs:
    resources:
      - name: source
        type: git
  steps:
    - name: npm-install
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm install
      workingDir: /workspace/source
    - name: build
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - npm run build
      workingDir: /workspace/source
    - name: copy-dist
      image: node
      command:
        - /bin/sh
        - -c
      args:
        - cp -R ./dist/* $(workspaces.app-binary.path)
      workingDir: /workspace/source