apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: quarkus-image-from-git
spec:
 inputs:
  resources:
    - name: git-source
      type: git
  params:
    - name: contextDir
      default: /workspace/git-source
      description: The Docker build context Dir
    - name: mavenMirrorUrl
      default: "https://repo1.maven.org/maven2"
      description: The MAVEN_MIRROR_URL url to use
    - name: mavenCmdArgs
      default: "clean -DskipTests install -Pnative"
      description: The maven command parameter
    - name: runScript
      default: "/usr/local/bin/buildah.sh"
      description: The script to use during
    - name: push
      default: "true"
      description: Whether to push the image to container registry or not
 outputs:
  resources:
    - name: builtImage
      type: image
 steps:
    - name: buildah-build-push
      image: quay.io/gnunn/quarkus-java-builder:graal-19.2.1
      imagePullPolicy: IfNotPresent
      env:
      - name: MAVEN_MIRROR_URL
        value: "${inputs.params.mavenMirrorUrl}"
      - name: WORK_DIR
        value: "${inputs.params.contextDir}"
      - name: PUSH
        value: "${inputs.params.push}"
      - name: MVN_CMD_ARGS
        value: "${inputs.params.mavenCmdArgs}"
      - name: DESTINATION_NAME
        value: ${outputs.resources.builtImage.url}
      args:
       - "${inputs.params.runScript}"
      securityContext:
        privileged: true
        capabilities:
          add: ["SYS_ADMIN"]
      volumeMounts:
        - mountPath: /root/.m2
          name: m2-cache
 volumes:
    - name: m2-cache
      persistentVolumeClaim:
        claimName: m2-cache